document.addEventListener('DOMContentLoaded', () => {
    const postsContainer = document.getElementById('posts-container');
    const tabButtons = document.querySelectorAll('.tab-btn');
    const currentTabTitle = document.getElementById('current-tab-title');

    let redditData = null;

    // Fetch the data generated by the automation
    async function loadData() {
        try {
            // Adjust path depending on where the server is run. 
            // Running python -m http.server from the root directory makes .tmp available.
            const response = await fetch('../.tmp/reddit_top_5.json');
            if (!response.ok) {
                throw new Error('Falha ao carregar o JSON.');
            }
            redditData = await response.json();

            // Render initial tab (n8n)
            renderPosts('n8n');
        } catch (error) {
            postsContainer.innerHTML = `
                <div class="post-card" style="text-align:center; color: #ff5555;">
                    <h3>Erro ao carregar dados</h3>
                    <p>Execute a automação Python primeiro para gerar o arquivo .tmp/reddit_top_5.json</p>
                    <p style="font-size:0.8rem; margin-top:10px;">${error.message}</p>
                </div>
            `;
        }
    }

    function timeSince(date) {
        const seconds = Math.floor((new Date() - new Date(date * 1000)) / 1000);
        let interval = seconds / 86400;
        if (interval > 1) return Math.floor(interval) + " dias atrás";
        interval = seconds / 3600;
        if (interval > 1) return Math.floor(interval) + " hr atrás";
        interval = seconds / 60;
        if (interval > 1) return Math.floor(interval) + " min atrás";
        return Math.floor(seconds) + " seg atrás";
    }

    function renderPosts(subreddit) {
        if (!redditData || !redditData[subreddit]) return;

        const posts = redditData[subreddit];
        postsContainer.innerHTML = '';
        currentTabTitle.innerHTML = `Posts Populares: <span class="highlight">r/${subreddit}</span>`;

        posts.forEach(post => {
            const card = document.createElement('div');
            card.className = 'post-card';
            card.innerHTML = `
                <div class="post-meta">
                    <img src="https://ui-avatars.com/api/?name=${post.author}&background=random&color=fff&size=32" style="border-radius:50%">
                    <span class="post-author">@${post.author}</span>
                    <span style="color:var(--text-muted)">•</span>
                    <span class="post-time">${timeSince(post.created_utc)}</span>
                </div>
                <div class="post-title">${post.title}</div>
                <div class="post-footer">
                    <div class="post-stats">
                        <span>💬 ${post.num_comments} Comments</span>
                        <span>⬆ ${post.score} Upvotes</span>
                        <span>🔥 ${post.engagement} Engajamento</span>
                    </div>
                    <a href="${post.url}" target="_blank" class="btn-link">Ver Post</a>
                </div>
            `;
            postsContainer.appendChild(card);
        });
    }

    // Tab Event Listeners
    tabButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            // Remove active class from all
            tabButtons.forEach(b => b.classList.remove('active'));
            // Add active class to clicked
            btn.classList.add('active');

            // Render new data
            const tabName = btn.getAttribute('data-tab');
            renderPosts(tabName);
        });
    });

    // Refresh Data button logic
    const refreshBtn = document.querySelector('.primary-btn');
    refreshBtn.addEventListener('click', () => {
        refreshBtn.innerText = "Carregando...";
        loadData().then(() => {
            refreshBtn.innerText = "Atualizar Dados";
        });
    });

    // Init
    loadData();
});
